### ISSUE TITLE
[Xerrada] Pipeline al cloud

### ISSUE THREAD

**Issue by jkngale** [GeeksCAT/gt-datascience#2]
Hola data scientist!

Per fer la primera trobada podriem començar amb aquesta petita xerrada per explicar com fer servir eines del cloud, en aquest cas Google Cloud Platform, per poder dissenyar, implementar i mantenir projectes automàtics de dades i els avantatges.

### Menú del dia

---

1. Introducció a Google Cloud
    1. BigQuery ML
    2. Cloud Storage
    3. Consultes programades
    4. Datastudio
2. Data input
    1. Google Analytics
    2. Cloud Storage
        1. Pentaho (ETL) per sincronitzar DWH
        2. CSV upload
3. Estructura de dades a BigQuery
4. Models de BigQuery ML
    1. K-Means
    2. Arima plus
    3. XGBoost
    4. Matrix Factorization
5. IDE Web
    1. SQL
    2. Funcions i procediments
6. Comparativa flow Cloud vs. Flow DWH + private server
7. Exemple: Creació d’un recomanador de productes
8. Preguntes + Easter Egg

**Comment by XaviTorello** [comment]
Xerrada realitzada el 22/11/22. Molt interessant, gràcies @jkngale
